### ISSUE TITLE
Repository Cleanup

### ISSUE THREAD

**Issue by capriciousalex** [prgpmc/PRG-MissionTemplate#1]
We need to cleanup the repository after the import, should be a good way to learn how Git works.

**TODO:**
- [x] Create a new branch named `jeremy/cleanup`
- [x] Remove `LICENSE` file
- [x] Create a pull request named `Cleanup Repository`, give it the `pr/wip` label, and enter the description `closes #1`
- [x] Update `README.md` with new repository name
- [x] Delete entire `/addons/*` directory and contents
- [x] Rename `/Missions/src/mission.vr` folder to `arma`
- [x] Move `/Missions/src` folder to root directory
- [x] Delete `Missions` folder once above is done
- [x] Change the `pr/wip` label to `pr/rdy` and add `capriciousalex` for review
